version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: lakemart-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lakemart
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - lakemart-net

  redis:
    image: redis:7-alpine
    container_name: lakemart-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - lakemart-net

  zookeeper:
    image: zookeeper:3.7
    container_name: lakemart-zookeeper
    ports:
      - "2181:2181"
    networks:
      - lakemart-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: lakemart-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost   # 修改点：将 kafka 改为 localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-actions:1:1"
    ports:
      - "9092:9092"
    networks:
      - lakemart-net

  spark:
    image: apache/spark:4.0.0-scala2.13-java21-ubuntu
    container_name: lakemart-spark
    depends_on:
      - kafka
      - redis
    volumes:
      - ./lakemart-spark/target/lakemart-spark.jar:/app/lakemart-spark.jar
      - ./data/spark-checkpoints:/tmp/spark/checkpoints
    command: >
      /opt/spark/bin/spark-submit
      --class org.lzx.lakemart.spark.HotItemsStreaming
      --master local[*]
      /app/lakemart-spark.jar
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - REDIS_HOST=redis
    networks:
      - lakemart-net

  minio:
    image: minio/minio
    container_name: lakemart-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - lakemart-net

networks:
  lakemart-net:
    driver: bridge