server:
  port: 8080

spring:
  application:
    name: lakemart-server
#  profiles:
#    active: dev   # ✅ 新增这一行：激活 dev 环境，让 DataSimulator 启动
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:lakemart}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  ai:
    zhipuai:
      zhipu:
        api-key: cb7268f94330442bac35de280f048a92.aP3qOBQQjbDzjdKm
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USERNAME:your-email@qq.com}
    password: ${MAIL_PASSWORD:your-auth-code}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: ${MINIO_BUCKET_NAME:lakemart}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-for-jwt-lakemart-project-2026}
  expiration: ${JWT_EXPIRATION:86400000}

temp:
  file:
    path: ${TEMP_FILE_PATH:./temp}

logging:
  level:
    # 你自己的服务日志（保持 DEBUG，方便调试）
    org.lzx.lakemart: DEBUG

    # 这些太吵了，调成 WARN 或 ERROR
    org.springframework: WARN
    org.springframework.web.socket: WARN
    org.springframework.messaging: WARN
    org.lzx.lakemart.task.SparkBatchScheduler: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.mybatis: WARN
    com.zaxxer.hikari: WARN
    root: WARN
# Spark 批处理调度配置（使用 java -cp 方式）
spark:
  java17:
    path: "D:/tool/JAVA/JDK17/bin/java.exe"
  fat:
    jar:
      path: "D:/MyDemo/LakeMart/lakemart-spark/target/lakemart-spark-1.0-SNAPSHOT.jar"

abtest:
  experiment:
    ratio: 0.1   # 10% 用户进入 ALS 实验组